### ISSUE TITLE
Blas/Voic files always throw Argument Exception

### ISSUE THREAD

**Issue by lovalmidas** [MikeG621/LfdReader#1]
When used in conjunction with the Sound Editor, the Blas / Voic files always throw an exception: "Raw header is not for a Blas or Voic resource"

To resolve, this should be changed:

**LfdReader/Blas.cs/Line 111** 
`if (_type != ResourceType.Blas || _type != ResourceType.Voic) throw new ArgumentException("Raw header is not for a Blas or Voic resource");`

to

`if (_type != ResourceType.Blas && _type != ResourceType.Voic) throw new ArgumentException("Raw header is not for a Blas or Voic resource");`

**Comment by MikeG621** [comment]
Fixed and uploaded v1.2.1 of the library, load that and you should be set.

**Comment by MikeG621** [comment]
And you'll probably need to also grab the [Common library](https://github.com/MikeG621/Common/releases/tag/v1.3.1) as well.

**Comment by MikeG621** [comment]
[TSE](https://github.com/MikeG621/TieSoundEditor/releases/tag/v1.2) updated and released.
